apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: zad2gitops 
              image: vicat28/cloud-app-operator:latest
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/pawelp29/cloud_z2_config.git /tmp/cloud_z2_config && kubectl apply -f /tmp/cloud_z2_config/deployment.yaml && kubectl apply -f /tmp/cloud_z2_config/service.yaml && kubectl apply -f /tmp/cloud_z2_config/ingress.yaml
